### ISSUE TITLE
Update header format

### ISSUE THREAD

**Issue by cvazac** [tuupola/server-timing-middleware#5]
Please note that the response header format has evolved:
Old:
```
Server-Timing: <name>=<duration>; <description>
```

New:
```
Server-Timing: <name>; dur=<duration>; desc=<description>
```

Example:
```
Server-Timing: db; dur=123.4; desc="database access"
```

[Spec PR](https://github.com/w3c/server-timing/commit/1cf183e08407ada77da62e628422fea8ff45b64a)

[Updates in Chrome](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/network/HTTPParsersTest.cpp?q=parseservertiming&sq=package:chromium&l=533)

**Comment by tuupola** [comment]
Again? Thanks for the heads up!

**Comment by cvazac** [comment]
Yes, but I think (hope!) that we are finally settled.

**Comment by tuupola** [comment]
Fixed with https://github.com/tuupola/server-timing-middleware/commit/76e16b72c69c0f7facc1a92d43e84ae71b088931. Will release when Chrome 66 is out.
